#cloud-config
autoinstall:
  version: 1
  
  packages:
    - ubuntu-desktop
    - curl
    - gnupg
    - wget
    
  snaps:
    - name: firefox
    - name: gnome-3-38-2004
    - name: gtk-common-themes
    - name: snap-store
    - name: snapd-desktop-integration
    
  identity:
    realname: 'Ubuntu User'
    username: ubuntu
    password: "$6$/EJRTPAuFLF6UCDQ$hoJf/WCXALcxXLHuc4cqyryVFH10nAgmsZiXbR4w.DoApeiCklhhkrduphh.aifM6EVtxh6AeewOenEFAh.YO0"
    hostname: ubuntu-desktop
    
  locale: de_DE.UTF-8
  keyboard:
    layout: de
    variant: ""
    
  storage:
    layout:
      name: direct
      
  # KORRIGIERT: Für Ubuntu 24.04 den Standard-Kernel verwenden
  early-commands:
    - echo 'linux-generic' > /run/kernel-meta-package
    
late-commands:
    # Passwort-Änderung
    - curtin in-target -- bash -c 'if id ubuntu >/dev/null 2>&1; then passwd -e ubuntu; fi'
    
    # Boot-Splash
    - >-
      curtin in-target -- sed -i /etc/default/grub -e
      's/GRUB_CMDLINE_LINUX_DEFAULT=".*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/'
    - curtin in-target -- update-grub
    
    # NetworkManager
    - rm -f /target/etc/netplan/00-installer-config*yaml
    - >-
      printf "network:\n  version: 2\n  renderer: NetworkManager"
      > /target/etc/netplan/01-network-manager-all.yaml
      
    # Microsoft Repos und Pakete
    - curtin in-target -- wget -qO /tmp/microsoft.asc https://packages.microsoft.com/keys/microsoft.asc
    - curtin in-target -- gpg --dearmor --output /usr/share/keyrings/microsoft.gpg /tmp/microsoft.asc
    - curtin in-target -- rm /tmp/microsoft.asc
    - >-
      curtin in-target -- bash -c 
      'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
    - >-
      curtin in-target -- bash -c 
      'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main" > /etc/apt/sources.list.d/microsoft-intune-portal.list'
    - curtin in-target -- apt-get update || true
    - curtin in-target -- apt-get install -y microsoft-edge-stable intune-portal || true
    
    # Netlution Setup Script von GitHub holen
    - curtin in-target -- wget -O /home/ubuntu/netlution-setup.sh https://raw.githubusercontent.com/junet-1/Intune-Linux/refs/heads/main/netlution_setup.sh
    - curtin in-target -- chmod +x /home/ubuntu/netlution-setup.sh
    - curtin in-target -- chown ubuntu:ubuntu /home/ubuntu/netlution-setup.sh
    
    # Autostart beim ersten Login
    - curtin in-target -- mkdir -p /home/ubuntu/.config/autostart
    - >-
      curtin in-target -- bash -c 'cat > /home/ubuntu/.config/autostart/netlution-setup.desktop << "EOF"
      [Desktop Entry]
      Type=Application
      Name=Netlution Setup
      Exec=/home/ubuntu/netlution-setup.sh
      Hidden=false
      NoDisplay=true
      X-GNOME-Autostart-enabled=true
      EOF'
    - curtin in-target -- chown -R ubuntu:ubuntu /home/ubuntu/.config
    
    # Cleanup
    - curtin in-target -- apt-get autoremove -y
