#cloud-config
autoinstall:
  version: 1
  
  packages:
    - ubuntu-desktop
    - curl
    - gnupg
    - wget
    - zenity
    - libnotify-bin
    
  snaps:
    - name: firefox
    - name: gnome-3-38-2004
    - name: gtk-common-themes
    - name: snap-store
    - name: snapd-desktop-integration
    
  identity:
    realname: 'Ubuntu User'
    username: ubuntu
    password: "$6$/EJRTPAuFLF6UCDQ$hoJf/WCXALcxXLHuc4cqyryVFH10nAgmsZiXbR4w.DoApeiCklhhkrduphh.aifM6EVtxh6AeewOenEFAh.YO0"
    hostname: ubuntu-desktop
    
  locale: de_DE.UTF-8
  keyboard:
    layout: de
    variant: ""
    
  storage:
    layout:
      name: direct
      
  early-commands:
    - echo 'linux-generic' > /run/kernel-meta-package
    
  late-commands:
    # Passwort-Änderung
    - curtin in-target -- bash -c 'if id ubuntu >/dev/null 2>&1; then passwd -e ubuntu; fi'
    
    # Boot-Splash aktivieren
    - >-
      curtin in-target -- sed -i /etc/default/grub -e
      's/GRUB_CMDLINE_LINUX_DEFAULT=".*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/'
    - curtin in-target -- update-grub
    
    # NetworkManager konfigurieren
    - rm -f /target/etc/netplan/00-installer-config*yaml
    - >-
      printf "network:\n  version: 2\n  renderer: NetworkManager"
      > /target/etc/netplan/01-network-manager-all.yaml
      
    # Microsoft GPG-Key installieren
    - curtin in-target -- wget -qO /tmp/microsoft.asc https://packages.microsoft.com/keys/microsoft.asc
    - curtin in-target -- gpg --dearmor --output /usr/share/keyrings/microsoft.gpg /tmp/microsoft.asc
    - curtin in-target -- rm /tmp/microsoft.asc
    
    # Microsoft Repositories
    - >-
      curtin in-target -- bash -c 
      'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
    - >-
      curtin in-target -- bash -c 
      'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main" > /etc/apt/sources.list.d/microsoft-intune-portal.list'
      
    # Microsoft Pakete installieren
    - curtin in-target -- apt-get update || true
    - curtin in-target -- apt-get install -y microsoft-edge-stable || true
    - curtin in-target -- apt-get install -y intune-portal || true
    
    # Netlution Setup Script nach /tmp (als root zugänglich)
    - curtin in-target -- wget -O /tmp/netlution-setup.sh https://raw.githubusercontent.com/junet-1/Intune-Linux/refs/heads/main/netlution-setup.sh || true
    - curtin in-target -- wget -O /tmp/netlution-setup.desktop https://raw.githubusercontent.com/junet-1/Intune-Linux/refs/heads/main/netlution-setup.desktop || true
    - curtin in-target -- chmod +x /tmp/netlution-setup.sh
    
    # Setup-Installer Script erstellen (läuft beim ersten Login)
    - >-
      curtin in-target -- bash -c 'cat > /usr/local/bin/netlution-first-login << "EOF"
      #!/bin/bash
      if [[ ! -f /home/ubuntu/.config/netlution-setup-installed ]]; then
          mkdir -p /home/ubuntu/.config/autostart
          cp /tmp/netlution-setup.sh /home/ubuntu/netlution-setup.sh 2>/dev/null || true
          cp /tmp/netlution-setup.desktop /home/ubuntu/.config/autostart/ 2>/dev/null || true
          chmod +x /home/ubuntu/netlution-setup.sh 2>/dev/null || true
          chown -R ubuntu:ubuntu /home/ubuntu/.config 2>/dev/null || true
          chown ubuntu:ubuntu /home/ubuntu/netlution-setup.sh 2>/dev/null || true
          touch /home/ubuntu/.config/netlution-setup-installed
          /home/ubuntu/netlution-setup.sh &
      fi
      EOF'
    - curtin in-target -- chmod +x /usr/local/bin/netlution-first-login
    
    # .profile anpassen für automatische Ausführung
    - curtin in-target -- bash -c 'echo "[ ! -f ~/.config/netlution-setup-installed ] && /usr/local/bin/netlution-first-login &" >> /home/ubuntu/.profile'
    
    # Server-Pakete entfernen
    - >-
      curtin in-target -- apt-get remove -y
      btrfs-progs cryptsetup* lvm2 xfsprogs
      ubuntu-server ubuntu-server-minimal
      
    # Cloud-init behalten
    - curtin in-target -- apt-get install -y cloud-init
    - curtin in-target -- apt-get autoremove -y
