#cloud-config
autoinstall:
  version: 1
  
  packages:
    - ubuntu-desktop
    - curl
    - gnupg
    - wget
    
  snaps:
    - name: firefox
    - name: gnome-3-38-2004
    - name: gtk-common-themes
    - name: snap-store
    - name: snapd-desktop-integration
    
  identity:
    realname: 'Ubuntu User'
    username: ubuntu
    password: "$6$/EJRTPAuFLF6UCDQ$hoJf/...OH.YO0"
    hostname: ubuntu-desktop
    
  locale: de_DE.UTF-8
  keyboard:
    layout: de
    variant: ""
    
  storage:
    layout:
      name: direct
      
  # Für Ubuntu 24.04 den Standard-Kernel verwenden
  early-commands:
    - echo 'linux-generic' > /run/kernel-meta-package
    
  late-commands:
    # Prüfen ob User existiert und ggf. Passwort-Änderung
    - curtin in-target -- bash -c 'if id ubuntu >/dev/null 2>&1; then passwd -e ubuntu; fi'
    
    # Boot-Splash aktivieren
    - >-
      curtin in-target -- sed -i /etc/default/grub -e
      's/GRUB_CMDLINE_LINUX_DEFAULT=".*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/'
    - curtin in-target -- update-grub
    
    # NetworkManager konfigurieren
    - rm -f /target/etc/netplan/00-installer-config*yaml
    - >-
      printf "network:\n  version: 2\n  renderer: NetworkManager"
      > /target/etc/netplan/01-network-manager-all.yaml
      
    # Server-Pakete entfernen
    - >-
      curtin in-target -- apt-get remove -y
      btrfs-progs cryptsetup* lvm2 xfsprogs
      ubuntu-server ubuntu-server-minimal
      
    # Cloud-init behalten
    - curtin in-target -- apt-get install -y cloud-init
    - curtin in-target -- apt-get autoremove -y
    
    # Microsoft-Pakete später installieren (Post-Boot-Script)
    - >-
      curtin in-target -- bash -c 'cat > /home/ubuntu/install-microsoft.sh << EOF
      #!/bin/bash
      wget -qO /tmp/microsoft.asc https://packages.microsoft.com/keys/microsoft.asc
      sudo gpg --dearmor --output /usr/share/keyrings/microsoft.gpg /tmp/microsoft.asc
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge.list
      sudo apt-get update
      sudo apt-get install -y microsoft-edge-stable
      rm /tmp/microsoft.asc
      EOF'
    - curtin in-target -- chmod +x /home/ubuntu/install-microsoft.sh
