#cloud-config
autoinstall:
  version: 1
  
  packages:
    - ubuntu-desktop
    - curl
    - gnupg
    - wget
    - gnome-keyring  # Keyring wird bei Login aktiviert
    - libsecret-1-0
    
  snaps:
    - name: firefox
    - name: gnome-3-38-2004
    - name: gtk-common-themes
    - name: snap-store
    - name: snapd-desktop-integration
    
  identity:
    realname: 'Ubuntu User'
    username: ubuntu
    password: "$6$/EJRTPAuFLF6UCDQ$hoJf/WCXALcxXLHuc4cqyryVFH10nAgmsZiXbR4w.DoApeiCklhhkrduphh.aifM6EVtxh6AeewOenEFAh.YO0"
    hostname: ubuntu-desktop
    
  locale: de_DE.UTF-8
  keyboard:
    layout: de
    variant: ""
    
  storage:
    layout:
      name: direct
      
  # KORRIGIERT: Für Ubuntu 24.04 den Standard-Kernel verwenden
  early-commands:
    - echo 'linux-generic' > /run/kernel-meta-package
    
  late-commands:
    # Prüfen ob User existiert und ggf. Passwort-Änderung
    - curtin in-target -- bash -c 'if id ubuntu >/dev/null 2>&1; then passwd -e ubuntu; fi'
    
    # Boot-Splash aktivieren
    - >-
      curtin in-target -- sed -i /etc/default/grub -e
      's/GRUB_CMDLINE_LINUX_DEFAULT=".*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/'
    - curtin in-target -- update-grub
    
    # NetworkManager konfigurieren
    - rm -f /target/etc/netplan/00-installer-config*yaml
    - >-
      printf "network:\n  version: 2\n  renderer: NetworkManager"
      > /target/etc/netplan/01-network-manager-all.yaml
      
    # Microsoft Repository VORBEREITEN (nicht installieren!)
    - curtin in-target -- wget -qO /tmp/microsoft.asc https://packages.microsoft.com/keys/microsoft.asc
    - curtin in-target -- gpg --dearmor --output /usr/share/keyrings/microsoft.gpg /tmp/microsoft.asc
    - curtin in-target -- rm /tmp/microsoft.asc
    
    # First-Login-Script erstellen (läuft wenn Benutzer sich anmeldet)
    - >-
      curtin in-target -- bash -c 'cat > /home/ubuntu/setup-intune-first-login.sh << "EOF"
      #!/bin/bash
      # Intune Setup beim ersten Login
      
      # Log-Datei
      LOGFILE="/home/ubuntu/intune-setup.log"
      echo "$(date): Intune Setup gestartet" >> "$LOGFILE"
      
      # Microsoft Repositories hinzufügen
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge.list
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main" | sudo tee /etc/apt/sources.list.d/microsoft-intune-portal.list
      
      # Repositories aktualisieren
      sudo apt-get update
      
      # Java 11 installieren (wichtig für Intune!)
      sudo apt-get install -y openjdk-11-jre
      sudo apt-get purge -y openjdk-21-jre-headless default-jre-headless || true
      
      # Java 11 als Standard setzen
      sudo update-alternatives --set java /usr/lib/jvm/java-11-openjdk-amd64/bin/java || true
      
      # Microsoft-Pakete installieren (jetzt mit aktivem Keyring!)
      sudo apt-get install -y microsoft-edge-stable intune-portal
      
      # Intune Cache löschen (falls vorhanden)
      rm -rf ~/.cache/intune-portal
      
      echo "$(date): Intune Setup abgeschlossen" >> "$LOGFILE"
      echo "System ist bereit für Intune Enrollment!"
      echo "Starte: intune-portal"
      
      # Script nach erfolgreichem Ausführen löschen
      rm -f /home/ubuntu/setup-intune-first-login.sh
      rm -f /home/ubuntu/.config/autostart/intune-setup.desktop
      EOF'
    
    # Autostart-Entry erstellen (läuft beim ersten Login automatisch)
    - curtin in-target -- mkdir -p /home/ubuntu/.config/autostart
    - >-
      curtin in-target -- bash -c 'cat > /home/ubuntu/.config/autostart/intune-setup.desktop << "EOF"
      [Desktop Entry]
      Type=Application
      Name=Intune Setup
      Exec=/home/ubuntu/setup-intune-first-login.sh
      Hidden=false
      NoDisplay=false
      X-GNOME-Autostart-enabled=true
      EOF'
    
    # Berechtigungen setzen
    - curtin in-target -- chmod +x /home/ubuntu/setup-intune-first-login.sh
    - curtin in-target -- chown -R ubuntu:ubuntu /home/ubuntu/.config
    - curtin in-target -- chown ubuntu:ubuntu /home/ubuntu/setup-intune-first-login.sh
    
    # Server-Pakete entfernen
    - >-
      curtin in-target -- apt-get remove -y
      btrfs-progs cryptsetup* lvm2 xfsprogs
      ubuntu-server ubuntu-server-minimal
      
    # Cloud-init behalten
    - curtin in-target -- apt-get install -y cloud-init
    - curtin in-target -- apt-get autoremove -y
