#cloud-config
autoinstall:
  version: 1
  
  # Standard Ubuntu Desktop Pakete
  packages:
    - ubuntu-desktop
    - curl
    - gnupg
    - wget
    - openssh-server  # Für Remote-Management
    
  # Standard Desktop Snaps
  snaps:
    - name: firefox
    - name: gnome-3-38-2004
    - name: gtk-common-themes
    - name: snap-store
    - name: snapd-desktop-integration
    
  # Benutzer-Konfiguration
  identity:
    realname: ''
    username: ubuntu
    # SHA-512 Hash von "NetUbuntu2025" - beim echten Deployment ersetzen
    password: "$6$/EJRTPAuFLF6UCDQ$hoJf/...OH.YO0"
    hostname: ubuntu-laptop
    
  # Deutsche Lokalisierung
  locale: de_DE.UTF-8
  keyboard:
    layout: de
    variant: ""
    
  # Einfaches Storage Layout für Laptops
  storage:
    layout:
      name: direct
      
  # HWE Kernel für bessere Hardware-Unterstützung
  early-commands:
    - echo 'linux-generic-hwe-22.04' > /run/kernel-meta-package
    
  # Post-Installation Konfiguration
  late-commands:
    # Passwort-Änderung beim ersten Login erzwingen
    - curtin in-target -- passwd -e ubuntu
    
    # Boot-Splash aktivieren
    - >-
      curtin in-target -- sed -i /etc/default/grub -e
      's/GRUB_CMDLINE_LINUX_DEFAULT=".*/GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"/'
    - curtin in-target -- update-grub
    
    # NetworkManager für Laptops (WLAN etc.)
    - rm -f /target/etc/netplan/00-installer-config*yaml
    - >-
      printf "network:\n  version: 2\n  renderer: NetworkManager"
      > /target/etc/netplan/01-network-manager-all.yaml
      
    # Microsoft Edge Repository hinzufügen
    - curtin in-target -- wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/microsoft.gpg
    - >-
      curtin in-target -- bash -c 
      'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list'
      
    # Intune Portal Repository hinzufügen
    - >-
      curtin in-target -- bash -c 
      'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" > /etc/apt/sources.list.d/microsoft-intune-portal.list'
      
    # Microsoft Pakete installieren
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get install -y microsoft-edge-stable intune-portal
    
    # Server-Pakete entfernen (nicht nötig auf Laptops)
    - >-
      curtin in-target -- apt-get remove -y
      btrfs-progs cryptsetup* lvm2 xfsprogs
      ubuntu-server ubuntu-server-minimal
      
    # SSH für Remote-Management konfigurieren
    - curtin in-target -- systemctl enable ssh
    
    # Cloud-init behalten für weitere Konfiguration
    - curtin in-target -- apt-get install -y cloud-init
    
    # Aufräumen
    - curtin in-target -- apt-get autoremove -y
